<?php
	$CLIENT_ID = "a0ziybzzlsgcgeb5mmj73svr5paqbu";
	$APP_TOKEN = "iiszijscwxj4o72fgy74fycgqiv75e";
	
	if ($_SERVER['REQUEST_METHOD'] != 'GET') {
		http_response_code(404);
		echo "Not Found.";
		exit(0);
	}
	
	// Generated by curl-to-PHP: http://incarnate.github.io/curl-to-php/
	$ch = curl_init();
	
	curl_setopt($ch, CURLOPT_URL, 'https://api.twitch.tv/helix/streams?user_login=volumetrique');
	curl_setopt($ch, CURLOPT_RETURNTRANSFER, 1);
	curl_setopt($ch, CURLOPT_CUSTOMREQUEST, 'GET');
	
	
	$headers = array();
	$headers[] = "Authorization: Bearer $APP_TOKEN";
	$headers[] = "Client-Id: $CLIENT_ID";
	curl_setopt($ch, CURLOPT_HTTPHEADER, $headers);
	
	$result = curl_exec($ch);
	$code = curl_getinfo($ch, CURLINFO_RESPONSE_CODE);
	$contentType = curl_getinfo($ch, CURLINFO_CONTENT_TYPE);
	if (curl_errno($ch)) {
		http_response_code(500);
		echo "Error:" . curl_error($ch);
		exit(0);
	}
	curl_close($ch);
	
	http_response_code($code);
	header("Content-Type: $contentType");
	echo $result;
	